name: Deploy NotionNext to EdgeOne

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build Next.js
        env:
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          NEXT_PUBLIC_THEME: next
        run: yarn build

    
      - name: Install EdgeOne CLI and Deploy
        env:
          TENCENTCLOUD_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENTCLOUD_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
        run: |
          npm install -g edgeone@0.1.35
          edgeone pages deploy .next --project-name pages
